### ISSUE TITLE
Support setting policy tags using Spark column's metadata

### ISSUE THREAD

**Issue by khaledh** [GoogleCloudDataproc/spark-bigquery-connector#1044] opened 2023-08-21 15:23 UTC
This is a feature request to support setting BigQuery policy tags on columns through Spark's [`metadata`](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.types.StructField.html?highlight=metadata) field attribute.

Without this feature, we have to resort to creating the table first using the bigquery python client with a schema that has the `SchemaField.policy_tags` set on the appropriate schema fields, and then asking the connector to write to the existing table. This has caused a [couple](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/1028) of [issues](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/1043) where the connector could drop the existing policy tags if they're not preserved properly.

**Comment by isha97** [comment] 2024-01-03 21:20
Duplicate of #1043

**Closed by isha97** 2024-01-03 21:20 UTC
