### ISSUE TITLE
rpc.UnavailableException with 0.21.0 on Dataproc

### ISSUE THREAD

**Issue by kamalmemon** [GoogleCloudDataproc/spark-bigquery-connector#406] opened 2021-06-04 12:02 UTC
Hi!

When using the latest release of spark-bq-connector available through the jar:

`"gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar"`

we run into to the following issue when executing jobs on dataproc:

```
py4j.protocol.Py4JJavaError: An error occurred while calling o625.collectToPython.
: com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.UnavailableException:
com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
```

Following is the pseudo code where we encounter this issue:
```
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()
spark.conf.set("viewsEnabled", "true")
spark.conf.set("materializationDataset", <MATERIALIZATION-DATASET>)

formatted_query = <SIMPLE-BQ-SELECT-QUERY>
df = spark.read.format("com.google.cloud.spark.bigquery").option("query", formatted_query).load()
df = df.filter(<FOO-FILTER>).select(<BAR-COLUMN>)
guz_col = <GUZ-COLUMN>
list_oi = [str(row[guz_col]) for row in df.select(guz_col).collect()]
```

We have since opted to pin the jar version and revert it to the penultimate release at:
`"gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.20.0.jar"`

And things are running smoothly since.

**Comment by davidrabinowitz** [comment] 2021-06-04 16:26
I'd appreciate it if you can add more information:
* Can you please attache full stack trace? 
* Which spark version is it?
* Are you running on Dataproc or or another environment?

Also, I've tried to reproduce it without success. Can you please try again?

**Comment by davidrabinowitz** [comment] 2021-06-07 20:47
Duplicate of #407

**Closed by davidrabinowitz** 2021-06-07 20:47 UTC
Labels: question
