### ISSUE TITLE
Job success but Data was not loaded into bigquery with direct write mode

### ISSUE THREAD

**Issue by kaiseu** [GoogleCloudDataproc/spark-bigquery-connector#1125] opened 2023-11-11 01:42 UTC
we use the spark bq connector with direct write mode to load the gcs files to bigquery tables, we found that the job was success but the data was not loaded into the target.

we checked the history log, the Spark tasks are all completed successfully.

we checked the driver log, only saw a warning message: 
WARN com.google.cloud.spark.bigquery.write.BigQueryDataSourceWriterInsertableRelation: It seems that 2 out of 26 partitions have failed, aborting 

this warning sees to be from this code, could you pls help check what's happening here?
<img width="824" alt="image" src="https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/7146858/85103dcf-5fe4-4aa4-b643-6ecee639e898">

also, we have verified the indirect mode works well.

connector verion: 0.32.2
spark version: 3.1.3
jdk: 1.8

**Comment by davidrabinowitz** [comment] 2023-11-13 17:06
Is this the same as Issue #1126 ?

**Comment by kaiseu** [comment] 2023-11-15 03:36
not the same. this job is reading from gcs files and write to bq, the jobs shows success but the actual data not loaded into bq. 

#1126 is reading from one bq table and write to another table, the job failed with error

**Comment by kaiseu** [comment] 2023-11-20 01:47
team, any suggestions on this?

**Comment by davidrabinowitz** [comment] 2023-11-20 21:15
Have you checked the executor logs?

**Comment by kaiseu** [comment] 2023-11-21 01:41
yes, everything looks well

**Comment by vishalkarve15** [comment] 2023-11-30 08:54
Can you please share the driver code you're using to write? I tried reproducing it with a 0.32.2 build modified to force it to fail but it does throw the correct exception and you can catch it in your application code.
```
try {
  df.write.format("bigquery").option("writeMethod","direct").save("xxx.yyy")
} catch {
  case e: Exception => println("my exception: " + e)
}
```

**Comment by kaiseu** [comment] 2023-12-15 10:01
the code is like this, first read from gcs file and write it to bq thru direct mode
 Dataset<Row> dataset = context.getSpark()
                .read()
                .option("multiline", true)
                .schema(structType)
                .format(format)
                .load(sourcePath);

dataset.write().mode(saveMode.getMode())
                .format("bigquery")
                .option("writeMethod", "direct")
                .option("enableModeCheckForSchemaFields", "false")
                .option(Constants.TABLE, fullTableName)
                .save();

can you try in case the gcs file are hundreds of small files and see?

**Comment by vishalkarve15** [comment] 2023-12-18 14:54
@kaiseu I'm unable to reproduce the issue. When I force it to fail using the code path `"It seems that xx out of xx partitions have failed, aborting"` , it correctly results in job failure.
Can you tell me where you see the job as successful, and also share the exact driver logs with the entire stack trace?

**Comment by vishalkarve15** [comment] 2024-01-02 08:39
Feel free to create a new issue with with above details. Closing for now.

**Closed by vishalkarve15** 2024-01-02 08:39 UTC
