### ISSUE TITLE
Behavior difference in BigQuery vs Hive when changing schema of a table with saveMode=overwrite

### ISSUE THREAD

**Issue by bbarodia** [GoogleCloudDataproc/spark-bigquery-connector#953] opened 2023-04-20 16:17 UTC
Hi,

We want to migrate our datastore from Hive to BigQuery. However we see the following differences in behavior and wanted to check if there are any flags we can pass in to make the behavior similar.

When adding a field or deleting a field in an existing table for a particular partition day, when we use `mode: overwrite`, Hive will not delete old partitions and still change the schema (add the column or delete it). 

However, when using BigQuery, the older partitions will get deleted and only the partition that we wrote remains. 

We have tried using the flags, `allowFieldAddition` during write but that does not work.

**Comment by davidrabinowitz** [comment] 2023-04-20 20:28
Duplicate of Issue #945

**Closed by davidrabinowitz** 2023-04-20 20:28 UTC
Labels: duplicate
