### ISSUE TITLE
can't write array struct to bigquery table for repeated record 

### ISSUE THREAD

**Issue by devbrian** [GoogleCloudDataproc/spark-bigquery-connector#474] opened 2021-10-06 15:13 UTC
In BigQuery, I have a field that is of type RECORD and in REPEATED mode, a column called actions. In Spark, I have a schema defined as

```
val action: StructType = (new StructType)
    .add("id", StringType)
    .add("name", StringType)
    .add("last", StringType)

val actionsList = new ArrayType(action, true)

val finalStruct: StructType = (new StructType)
    .add("recordName", StringType)
    .add("date", StringType)
    .add("actions", actionsList)
```

This is how my schema is defined, then I simply read it in and write it to bigquery.

In BigQuery, I have a field that is of type `RECORD` and in `REPEATED` mode, a column called `actions`.  In Spark, I have a schema defined as 

```
val action: StructType = (new StructType)
    .add("id", StringType)
    .add("name", StringType)
    .add("last", StringType)

val actionsList = new ArrayType(action, true)

val finalStruct: StructType = (new StructType)
    .add("recordName", StringType)
    .add("date", StringType)
    .add("actions", actionsList)
```

This is how my schema is defined, then I simply read it in and write it to bigquery.

```
val df = spark.read.schema(finalStruct).json(rdd)
df.write.mode("append").format("bigquery")...save()
```

However, when I attempt to write the dataframe, I get the error -

```
BigQuery error was provided Schema does not match Table <table_name_here>.  
Cannot add fields (field: actions.list)
```

What's the proper way to define this schema?  My data coming in is in json format like 

```
{
    "recordName":"name_here", 
    "date": "2020-01-01", 
    "actions": [
        {
            "id":"1", 
            "name":"aaa", 
            "last":"bbb"
        },
        {
            "id":"2", 
            "name":"qqq", 
            "last":"www"
        }
    ]
}
```

**Comment by davidrabinowitz** [comment] 2021-10-07 19:35
Please use the AVRO or ORC intermediate formats. 
Duplicate of Issue #251

**Closed by davidrabinowitz** 2021-10-07 19:35 UTC
Labels: duplicate
