### ISSUE TITLE
Issue with writing Date/Timestamp datatype in BigQuery using Indirect write method

### ISSUE THREAD

**Issue by pso-naithanan** [GoogleCloudDataproc/spark-bigquery-connector#612] opened 2022-05-03 23:10 UTC
When we are trying to _Append_ data  a big-query existing table with  the **_Indirect write method_** using _spark-bigquery-connector_(spark-2.4-bigquery-0.24.2-preview.jar) the job is failing.Please see the complete error stack in the end . After checking the big-query load job logs we see schema mismatch issue,below is the error 
_Provided Schema does not match Table <project_id>:<dataset>.test_trans_data. Field block_timestamp_month has changed type from DATE to INTEGER. We are only seeing this issue with the Date and Timestamp columns.

When we create a new table from py-spark df write, then the new table is created with the wrong datatype for Date and Timestamp columns, the datatype of these columns is Integer.

**Direct write does not cause any issue.**   

In our debugging we tried to print the schema of df(df.printSchema()) and there it looks fine , meaning columns with date and timestamp remain as it is. Below are the steps we followed to reproduce the above issue.
 
For debugging purpose we have to written the data in avro format file in gcs using pyspark dataframe and then used the bq load command by passing this flag(_use_avro_logical_types_) and the data was loaded with correct date format. 

```
bq load  --noreplace --use_avro_logical_types --source_format=AVRO <dataset>.some_data_tab_v1 gs://ttest_abucket_crt_2022/sample_data/test_res_iv_20220501/part*```

```
spark version 2.4.8
python version 3.7.4
spark-2.4-bigquery-0.24.2-preview.jar
```
 
```
Step 1 : Create a bigquery table with following schema
   create table <dataset-id>.test_trans_data(hash_t string,
       size integer ,
       virtual_size integer ,
       version integer ,
       lock_time integer ,
       block_hash string ,
       block_number integer ,
       block_timestamp timestamp ,
       block_timestamp_month date ,
       input_count integer ,
       output_count integer ,
       input_value numeric ,
       output_value numeric,
       is_coinbase boolean ,
       fee numeric)
Step 2 : Reading data from GCS bucket, data is in parquet format.
           df=spark.read.parquet("gs://ttest_data_20220501/sample_data/test_res_par_i_20220501/")
Step 3 : Write data to bigquery table using indirect write method
           df.write.format("bigquery").option("temporaryGcsBucket","test-20220501").mode("append").save("<dataset>.test_trans_data")

```

**_Complete error stack_** 

ERROR org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec: Data source writer com.google.cloud.spark.bigquery.v2.BigQueryDataSourceWriter@775d2a08 is aborting.
WARN com.google.cloud.spark.bigquery.v2.context.BigQueryIndirectDataSourceWriterContext: Aborting write e855cdd9-ef83-4aa1-954f-66535668a958 for table<project_id>:<dataset>.test_trans_data
ERROR org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec: Data source writer com.google.cloud.spark.bigquery.v2.BigQueryDataSourceWriter@775d2a08 aborted.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/spark/python/pyspark/sql/readwriter.py", line 742, in save
    self._jwrite.save(path)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/usr/lib/spark/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o71.save.
: org.apache.spark.SparkException: Writing job aborted.
        at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec.doExecute(WriteToDataSourceV2Exec.scala:92)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:136)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:160)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:157)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:132)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:83)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:81)
        at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:696)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:80)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:696)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:281)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:249)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NullPointerException
        at com.google.cloud.bigquery.connector.common.BigQueryClient.loadDataIntoTable(BigQueryClient.java:532)
        at com.google.cloud.spark.bigquery.v2.context.BigQueryIndirectDataSourceWriterContext.loadDataToBigQuery(BigQueryIndirectDataSourceWriterContext.java:161)
        at com.google.cloud.spark.bigquery.v2.context.BigQueryIndirectDataSourceWriterContext.commit(BigQueryIndirectDataSourceWriterContext.java:132)
        at com.google.cloud.spark.bigquery.v2.BigQueryDataSourceWriter.commit(BigQueryDataSourceWriter.java:51)
        at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec.doExecute(WriteToDataSourceV2Exec.scala:76)
        ... 25 more

**Comment by dmedora** [comment] 2022-05-04 16:11
To add a bit more detail - it seems that the cause is that `bq load` requires `--use_avro_logical_types` to map the Avro timestamp to a BQ timestamp (instead of BQ integer), as per the [docs](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-avro#logical_types). An option to provide this flag would probably resolve this. 

We also tried specifying `.option("intermediateFormat", "parquet")`, but it seems to still write to GCS as Avro. We thought loading to BQ from Parquet would be another solution since Parquet timestamps are automatically interpreted as BQ timestamps.

**Comment by JGrzywacz** [comment] 2022-05-24 07:45
Try `.option("intermediateFormat", "avro").option("useAvroLogicalTypes", "true")` 
It works for me

**Comment by pso-naithanan** [comment] 2022-05-29 03:24
@JGrzywacz , thanks this flag works for both direct and indirect write.

**Comment by VinayLondhe14** [comment] 2022-07-21 11:59
Closing this since a workaround exists

**Closed by VinayLondhe14** 2022-07-21 11:59 UTC
