### ISSUE TITLE
Using RangePartitioning possible?

### ISSUE THREAD

**Issue by dirk-gasser-db** [GoogleCloudDataproc/spark-bigquery-connector#939] opened 2023-03-27 13:55 UTC
Is it possible to use BQ RangePartitioning :
bq query \
    --use_legacy_sql=false \
    --destination_table PROJECT_ID:DATASET.TABLE \
    --range_partitioning COLUMN,START,END,INTERVAL \
    'QUERY_STATEMENT'

for writing a table?

**Comment by davidrabinowitz** [comment] 2023-03-27 16:57
Not yet, but it's on our roadmap

**Comment by davidrabinowitz** [comment] 2023-06-06 23:39
Duplicate of issue #867

**Closed by davidrabinowitz** 2023-06-06 23:39 UTC
Labels: duplicate
