### ISSUE TITLE
Unable to write to BQ from Spark

### ISSUE THREAD

**Issue by CharelzT90** [GoogleCloudDataproc/spark-bigquery-connector#657] opened 2022-06-02 05:55 UTC
Since yesterday I am no longer able to write to BQ from Spark even though the Schemas are identical I keep getting the following error:

`Caused by: java.lang.IllegalArgumentException: com.google.cloud.bigquery.connector.common.BigQueryConnectorException$InvalidSchemaException: Destination table's schema is not compatible with dataframe's schema`

I have checks in the code that will modify the schema in the source and destination. I even retried loading data that successfully loaded the day before and am still getting the same error even when setting.

`spark.conf.set("spark.datasource.bigquery.enableModeCheckForSchemaFields", "false")`

Using indirect write.

I observed that the columns have to be present in the source dataframe which seems backwards to me if they are NULLABLE and not REQUIRED? This allowed me to write into one of the tables after some trial and error. I also observed it doesn't appear to be respecting no order of the columns, I tried with another table that had the same columns just in a different order and got the error again.

Resorted to moving back to 0.24.2 for now.

**Comment by suryasoma** [comment] 2022-06-06 22:56
Hello @CharelzT90, the issue is fixed and the fix would be available in the next release

**Comment by kaiseu** [comment] 2022-06-13 06:10
same issue on 0.25.0, 0.24.2 is ok

**Comment by suryasoma** [comment] 2022-06-24 00:01
Hey @CharelzT90, please find the fix for this in the latest release 0.25.2
Thanks

**Closed by suryasoma** 2022-06-24 00:01 UTC
