### ISSUE TITLE
Support for partition overwrite of integer-based partitions

### ISSUE THREAD

**Issue by ngsalmon** [GoogleCloudDataproc/spark-bigquery-connector#970] opened 2023-05-09 22:44 UTC
BigQuery supports partitioning tables by integer in addition to dates, but neither creation of integer-based partition tables, nor partition overwriting of integer-based partitions appear to be currently supported.  I'd expect a syntax something like:

```
(
    df.write.format("bigquery")
    .mode('overwrite')
    .option("temporaryGcsBucket", "my-bucket")
    .option("partitionField", "my_int_partition")
    .option("partitionType", "INTEGER")
    .option("partition", "1000")
    .option("createDisposition", "CREATE_IF_NEEDED")
    .option("table", "my_project.my_dataset.my_table")
    .save()
)
```

Alternatively, the proposed `partition` option could be called `integerPartition` or `intPartition` to mirror `datePartition`, and could take an integer or a string (which would be cast to an integer).

Is there any form of workaround for this currently?

**Comment by suryasoma** [comment] 2023-05-16 23:17
Currently we do not support this. But we do have it in the pipeline to support it.

**Comment by davidrabinowitz** [comment] 2023-06-06 23:40
Duplicate of issue #867

**Closed by davidrabinowitz** 2023-06-06 23:40 UTC
Labels: duplicate, enhancement

**Comment by ngsalmon** [comment] 2023-06-06 23:56
The description on this Issue is much more thorough than #867 from what I see.  Also, the SO post linked to #867 appears to be related to range-based partitioning, which is different than what I'm proposing here for integer-based partition support. Are we sure this is a duplicate? Please advise.

**Comment by davidrabinowitz** [comment] 2023-06-07 00:45
We are bound by the partitioning offered by BigQuery, and it is [limited](https://cloud.google.com/bigquery/docs/partitioned-tables#types_of_partitioning) to one of two types:

1. Integer range partitioning, as described also in issue #867 
2. Date/Time partitioning (daily, hourly, monthly, or yearly)

The latter is already supported. The first one is the topic of issue #867. If there's an additional type, please elaborate below.
