### ISSUE TITLE
Support DecimalType with Flexible Precision and Scale

### ISSUE THREAD

**Issue by Athrun7** [GoogleCloudDataproc/spark-bigquery-connector#524] opened 2022-01-19 12:52 UTC
We have BQ table which has column with type numeric(33,4). Using direct write mode raise exception which says we must conform to Spark decimaltype(38,9), which cannot fit our case as we cannot change the BQ table schema. Is it possible to support other precision/scale decimaltype?

**Comment by davidrabinowitz** [comment] 2022-01-19 17:22
Duplicate of #525

**Closed by davidrabinowitz** 2022-01-19 17:22 UTC
Labels: duplicate
